pre-release-replacements = [
    {file="CHANGELOG.md", search="## Unreleased", replace="## Unreleased\n\n## {{version}} - {{date}}", exactly=1},
]
post-release-replacements = [
    {file="CHANGELOG.md", search="# ChangeLog", replace="# ChangeLog\n\n## Unreleased", exactly=1},
]